apiVersion: v1
kind: Service
metadata:
  name: health-hub-service
spec:
  selector:
    app: health-hub
  ports:
  - protocol: "TCP"
    port: 5555
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-hub-deployment
  labels:
    app: health-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-hub
  template:
    metadata:
      labels:
        app: health-hub
    spec:
      containers:
      - name: health-hub
        image: health-hub:1.0
        ports:
        - containerPort: 5000